/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Brand {
  'id' : bigint,
  'logo' : [] | [ExternalBlob],
  'name' : string,
}
export type Category = { 'Accessories' : null } |
  { 'Wearables' : null } |
  { 'Audio' : null } |
  { 'Smartphones' : null } |
  { 'LaptopsTablets' : null };
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isFeatured' : boolean,
  'category' : Category,
  'brand' : string,
  'rating' : number,
  'image' : [] | [ExternalBlob],
  'isNew' : boolean,
  'price' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[bigint], undefined>,
  'adminAddBrand' : ActorMethod<[string, [] | [ExternalBlob]], bigint>,
  'adminAddProduct' : ActorMethod<[Product], bigint>,
  'adminDeleteBrand' : ActorMethod<[bigint], undefined>,
  'adminDeleteProduct' : ActorMethod<[bigint], undefined>,
  'adminGetContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'adminUpdateBrand' : ActorMethod<
    [bigint, string, [] | [ExternalBlob]],
    undefined
  >,
  'adminUpdateProduct' : ActorMethod<[bigint, Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllBrands' : ActorMethod<[], Array<Brand>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBrandById' : ActorMethod<[bigint], Brand>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductsByBrand' : ActorMethod<[string], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getProductsSortedByPrice' : ActorMethod<[], Array<Product>>,
  'getStoreName' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<
    [
      {
        'name' : string,
        'email' : string,
        'message' : string,
        'phone' : string,
      },
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];