/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Category = IDL.Variant({
  'Accessories' : IDL.Null,
  'Wearables' : IDL.Null,
  'Audio' : IDL.Null,
  'Smartphones' : IDL.Null,
  'LaptopsTablets' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : Category,
  'brand' : IDL.Text,
  'rating' : IDL.Float64,
  'image' : IDL.Opt(ExternalBlob),
  'isNew' : IDL.Bool,
  'price' : IDL.Float64,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Brand = IDL.Record({
  'id' : IDL.Nat,
  'logo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat], [], []),
  'adminAddBrand' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [IDL.Nat], []),
  'adminAddProduct' : IDL.Func([Product], [IDL.Nat], []),
  'adminDeleteBrand' : IDL.Func([IDL.Nat], [], []),
  'adminDeleteProduct' : IDL.Func([IDL.Nat], [], []),
  'adminGetContactMessages' : IDL.Func(
      [],
      [IDL.Vec(ContactMessage)],
      ['query'],
    ),
  'adminUpdateBrand' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'adminUpdateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBrandById' : IDL.Func([IDL.Nat], [Brand], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getProductsSortedByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getStoreName' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func(
      [
        IDL.Record({
          'name' : IDL.Text,
          'email' : IDL.Text,
          'message' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Category = IDL.Variant({
    'Accessories' : IDL.Null,
    'Wearables' : IDL.Null,
    'Audio' : IDL.Null,
    'Smartphones' : IDL.Null,
    'LaptopsTablets' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : Category,
    'brand' : IDL.Text,
    'rating' : IDL.Float64,
    'image' : IDL.Opt(ExternalBlob),
    'isNew' : IDL.Bool,
    'price' : IDL.Float64,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Brand = IDL.Record({
    'id' : IDL.Nat,
    'logo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat], [], []),
    'adminAddBrand' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'adminAddProduct' : IDL.Func([Product], [IDL.Nat], []),
    'adminDeleteBrand' : IDL.Func([IDL.Nat], [], []),
    'adminDeleteProduct' : IDL.Func([IDL.Nat], [], []),
    'adminGetContactMessages' : IDL.Func(
        [],
        [IDL.Vec(ContactMessage)],
        ['query'],
      ),
    'adminUpdateBrand' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'adminUpdateProduct' : IDL.Func([IDL.Nat, Product], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllBrands' : IDL.Func([], [IDL.Vec(Brand)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBrandById' : IDL.Func([IDL.Nat], [Brand], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByBrand' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsSortedByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getStoreName' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func(
        [
          IDL.Record({
            'name' : IDL.Text,
            'email' : IDL.Text,
            'message' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };